# Generated by Django 5.1.4 on 2024-12-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
