# Generated by Django 5.1.4 on 2024-12-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0002_designation_slug_specialization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availebletime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authApi/images/'),
        ),
    ]
