# Generated by Django 5.1.4 on 2024-12-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0003_remove_doctor_availebletime_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availabletime',
            field=models.ManyToManyField(blank=True, null=True, to='authApi.availebletime'),
        ),
    ]
