# Generated by Django 5.1.4 on 2025-01-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0010_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
    ]
